### PR TITLE
Add Style CI 

### PR DESCRIPTION
**Pull request by TomKlotzPro**
## Description 
Add CI tool. 

## What do it change 

Add configuration file for style ci.

### CODE REVIEW

**Comment by nunomaduro** [comment]
What do you think about using phpcs instead?

**Comment by TomKlotzPro** [comment]
I think having both is still good. In case we do collaborative work, having a warning on style is valuable. WDYT ?  But definitely it's good to add phpcs.

**Comment by nunomaduro** [comment]
I think there is no need of having two coding style tools doing exactly the same thing.

**Comment by TomKlotzPro** [comment]
Ok I add phpcs and remove styleci 👍

**Pull request merged**
